# Generated by Django 2.1.7 on 2019-03-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Número de Teléfono/Celular')),
                ('correo_electronico', models.CharField(blank=True, max_length=128, null=True, verbose_name='Correo Electrónico')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Imagen de perfil')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenChef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes', verbose_name='Imagen')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_chef', to='chefs.Chef')),
            ],
        ),
    ]
